---
/config/smtp_servers:
  get:
    x-mojo-to: Config::SMTP::Servers#list
    operationId: listSMTPServers
    tags:
      - smtp_servers
    summary: List SMTP servers
    produces:
      - application/json
    parameters:
      - $ref: ../parameters.yaml#/match
      - $ref: ../parameters.yaml#/order_by
      - $ref: ../parameters.yaml#/page
      - $ref: ../parameters.yaml#/per_page
      - $ref: ../parameters.yaml#/q_param
      - $ref: ../parameters.yaml#/q_body
      - $ref: ../parameters.yaml#/q_header
    responses:
      "200":
        description: A list of SMTP servers
        schema:
          type: array
          items:
            $ref: ../definitions.yaml#/smtp_server
      "403":
        description: Access forbidden
        schema:
          $ref: ../definitions.yaml#/error
      "500":
        description: Internal error
        schema:
          $ref: ../definitions.yaml#/error
      "503":
        description: Under maintenance
        schema:
          $ref: ../definitions.yaml#/error
    x-koha-authorization:
      permissions:
        parameters: manage_smtp_servers
  post:
    x-mojo-to: Config::SMTP::Servers#add
    operationId: addSMTPServer
    tags:
      - smtp_servers
    summary: Add SMTP server
    parameters:
      - name: body
        in: body
        description: A JSON object representing a new SMTP server configuration
        required: true
        schema:
          $ref: ../definitions.yaml#/smtp_server
    produces:
      - application/json
    responses:
      "201":
        description: An SMTP server object
        schema:
          $ref: ../definitions.yaml#/smtp_server
      "401":
        description: Authentication required
        schema:
          $ref: ../definitions.yaml#/error
      "403":
        description: Access forbidden
        schema:
          $ref: ../definitions.yaml#/error
      "409":
        description: Conflict in creating resource
        schema:
          $ref: ../definitions.yaml#/error
      "500":
        description: Internal error
        schema:
          $ref: ../definitions.yaml#/error
      "503":
        description: Under maintenance
        schema:
          $ref: ../definitions.yaml#/error
    x-koha-authorization:
      permissions:
        parameters: manage_smtp_servers
"/config/smtp_servers/{smtp_server_id}":
  get:
    x-mojo-to: Config::SMTP::Servers#get
    operationId: getSMTPServer
    tags:
      - smtp_servers
    summary: Get SMTP server
    parameters:
      - $ref: ../parameters.yaml#/smtp_server_id_pp
    produces:
      - application/json
    responses:
      "200":
        description: An SMTP server object
        schema:
          $ref: ../definitions.yaml#/smtp_server
      "404":
        description: Object not found
        schema:
          $ref: ../definitions.yaml#/error
      "409":
        description: Conflict updating resource
        schema:
          $ref: ../definitions.yaml#/error
      "500":
        description: Internal error
        schema:
          $ref: ../definitions.yaml#/error
      "503":
        description: Under maintenance
        schema:
          $ref: ../definitions.yaml#/error
    x-koha-authorization:
      permissions:
        parameters: manage_smtp_servers
  put:
    x-mojo-to: Config::SMTP::Servers#update
    operationId: updateSMTPServer
    tags:
      - smtp_servers
    summary: Update SMTP server
    parameters:
      - $ref: ../parameters.yaml#/smtp_server_id_pp
      - name: body
        in: body
        description: An SMTP server object
        required: true
        schema:
          $ref: ../definitions.yaml#/smtp_server
    produces:
      - application/json
    responses:
      "200":
        description: An SMTP server object
        schema:
          $ref: ../definitions.yaml#/smtp_server
      "401":
        description: Authentication required
        schema:
          $ref: ../definitions.yaml#/error
      "403":
        description: Access forbidden
        schema:
          $ref: ../definitions.yaml#/error
      "404":
        description: Object not found
        schema:
          $ref: ../definitions.yaml#/error
      "500":
        description: Internal error
        schema:
          $ref: ../definitions.yaml#/error
      "503":
        description: Under maintenance
        schema:
          $ref: ../definitions.yaml#/error
    x-koha-authorization:
      permissions:
        parameters: manage_smtp_servers
  delete:
    x-mojo-to: Config::SMTP::Servers#delete
    operationId: deleteSMTPServer
    tags:
      - smtp_servers
    summary: Delete SMTP server
    parameters:
      - $ref: ../parameters.yaml#/smtp_server_id_pp
    produces:
      - application/json
    responses:
      "204":
        description: SMTP server deleted
      "401":
        description: Authentication required
        schema:
          $ref: ../definitions.yaml#/error
      "403":
        description: Access forbidden
        schema:
          $ref: ../definitions.yaml#/error
      "404":
        description: Object not found
        schema:
          $ref: ../definitions.yaml#/error
      "500":
        description: Internal error
        schema:
          $ref: ../definitions.yaml#/error
      "503":
        description: Under maintenance
        schema:
          $ref: ../definitions.yaml#/error
    x-koha-authorization:
      permissions:
        parameters: manage_smtp_servers
